spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      password: 1234
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
      name: ${job.name:NONE}

job:
  seatOccupyJob:
    showId: ${job.seatOccupyJob.showId:6}
  waitingJob:
    timeout: 7
    showId: ${job.waitingQueue.showId:6}
  lock:
    key: ${job.lockKey:LOCK}
  chunk:
    size: ${chunk.size:100}

scheduler:
  job:
    name: ${job.schedulerJob.name:waitingJob}

portone:
  api:
    key: PORTONE_API_KEY
    secret: PORTONE_API_SECRET

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace


cronexpression: '0/1 * * * * ?'