spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      password: 1234
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      name: ${job.name:NONE}

chunk:
  size: ${chunk.size:100}

portone:
  api:
    key: PORTONE_API_KEY
    secret: PORTONE_API_SECRET

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

