name: CD with Gradle
on:
  push:
    branches: [ "develop", "feature/issue-31" ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      - name: Make application.properties
        run: |
          touch ./ticketing-api/src/main/resources/application-prod.yml
          echo "${{ secrets.PROPERTIES }}" > ./ticketing-api/src/main/resources/application-prod.yml
        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Docker build & push to docker repo
        run: |
          cd ./ticketing-api
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/ticketing-server .
          docker push ${{ secrets.DOCKER_REPO }}/ticketing-server
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/ticketing-server:latest
            sudo docker run -d --log-driver=syslog -p 8080:8080 -e "SPRING_PROFILES_ACTIVE=prod" warmth424/ticketing-server:latest